### ISSUE TITLE
Uncaught TypeError: _webpackerReact2.default.initialize is not a function

### ISSUE THREAD

**Issue by tirdadc** [renchap/webpacker-react#20]
Thank you for putting together this gem, it made moving from `react-rails` to using `webpacker` a lot less painful.

At this point everything seems to be working but I do notice this error being thrown in the console by the `initialize` call:

```
Uncaught TypeError: _webpackerReact2.default.initialize is not a function
    at Object.<anonymous> (test.js:7)
    at __webpack_require__ (bootstrap b4a3b0c…:19)
    at validateFormat (bootstrap b4a3b0c…:65)
    at bootstrap b4a3b0c…:65
```

Here's my pack file:

```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import Test from 'components/test';
import WebpackerReact from 'webpacker-react';

WebpackerReact.register(Test);
WebpackerReact.initialize();

console.info('media planner loaded');
```

I'm using the latest version of Webpacker (revision `a85a3ab0eac6626af9da0efbda9320404114d675`). Any idea what may be causing this?

**Comment by renchap** [comment]
You are using the unreleased master but with the latest released NPM module.

You either need to use the 0.1.0 released version for both the gem and the NPM module, or switch both to git.

If you want to use the latest JS code, you need to clone the repo locally, compile the NPM package, and tell Yarn to use it for your project. Please see here for how to do so : https://github.com/renchap/webpacker-react#development

This project is still moving quickly and the API will not be frozen until 1.0.0 (targeted for the Rails 5.1 release), If you want to use the latest git version, I would advise you to keep an eye on the Changelog before updating.

**Comment by tirdadc** [comment]
I switched the line in my Gemfile to:

```
gem 'webpacker-react', "0.1.0"
```

and re-ran `bundle install`

I also made sure that I have `"webpacker-react": "0.1.0"` in my package.json and ran `./bin/yarn install --force`, but I still get the same issue. Shouldn't that insure that I'm on 0.1.0 across the board? I do see this too in my `yarn.lock`:

```
webpacker-react@0.1.0
```

**Comment by renchap** [comment]
You dont need the initialize call for 0.1.0: https://github.com/renchap/webpacker-react/tree/v0.1.0#usage

I will update the readme to point to the latest released documentation 🙂

**Comment by tirdadc** [comment]
Perfect, that solves it! :-)

I'll put together a blog post on this process since I don't think I'll be alone in moving to `webpacker` once 5.1 ships!
