### ISSUE TITLE
Possibility to use jbuilder json in react_component?

### ISSUE THREAD

**Issue by cinqi** [renchap/webpacker-react#22]
react_component seems to convert passed data to json, so if I try to input props as jbuilder json 

`<%= react_component('Products', data: render(template: 'api/v1/products/index.json.jbuilder') ) %>`

In this case react_component converts json to json thus making it unreadable for React. 

`data: "{\"products\":[{\"id\":5,\"name\":\"Product 1\",....`

Would it be possible to use jbuilder to input props to React component? This is similar functionality as react_rails has.

**Comment by cinqi** [comment]
A bit further study revelead that I could use options to achieve this:

`<%= react_component('Products', options=render(template: 'api/v1/products/index.json.jbuilder') ) %>`

The json has products and product_type objects and with this I get this.props.products and this.props.product_types.

**Comment by renchap** [comment]
I am not sure to understand the syntax you used here. Is this working?
```erb
<%= react_component('Products', render(template: 'api/v1/products/index.json.jbuilder') ) %>
```

**Comment by cinqi** [comment]
That does not work. 

The idea would be to use jbuilder generater json as an input for React component. I looked at the react_component code and it does conversion .to_json. That is ok when you use class instance variable from controller. However, the options parameter in react_component are not converted to json, so when I pass json via options to React component, those are set as props correctly. So basically there is a way to pass already generated json to component without any change to existing implementation.

I prefer to generate json responses with jbuilder instead of selecting the displayed fields in the controller.  For this particular case I actually kept the original plan that I fetch the products in React lifecycle method componentDidMount. But for example I'm thinking of altering my code so that some form data (dropdown value/text lists etc) are passed on as json to component instead of component fetching the form parameters when form is loaded.

**Comment by sealocal** [comment]
The view helper expects options to be a `Hash`, not JSON.  You could parse your JSON into a hash before passing to the view helper.

```ruby
<%= react_component('Products', JSON.parse( render(template: 'api/v1/products/index.json') )) %>
```

Then you should able to access props:
```js
// case depends on your json template
this.props.updated_at.name
this.props.updatedAt.name
```

**Comment by cinqi** [comment]
Will test this at some point, closing this issue.

**Comment by tchret** [comment]
thanks @sealocal 👍
