### ISSUE TITLE
webpacker-react: cant render a component that has not been registered: Test

### ISSUE THREAD

**Issue by tirdadc** [renchap/webpacker-react#23]
After getting everything running on development, I finally tried rolling out my new Webpacker based setup to production, and I'm getting this error.

Test is registered normally in my pack and this works on development just fine:

```js
import Test from 'components/test';
import WebpackerReact from 'webpacker-react';

WebpackerReact.register(Test);
```

Is there any additional step needed for the `react_component` helper to work in production?

**Comment by renchap** [comment]
This is a known issue with 0.1.0, this will be fixed in the next version.
In the meantime, you can change `config/webpack/production.js` to not mangle the name of your root components:

```es6
    new webpack.optimize.UglifyJsPlugin({
      mangle: {
        except: ['Test'] // remove this once webpacker-react 0.2 is released
      }
    }),
```

**Comment by tirdadc** [comment]
That worked, I'll add it to my [write-up](https://tirdadc.github.io/blog/2017/03/07/migrating_from_react_rails_to_webpacker/). Thanks!

**Comment by renchap** [comment]
The new version is now released and fixes this issue!
Please look at the CHANGELOG, the API changed (`setup` replaced `register`).
