### ISSUE TITLE
Can't render a component in production

### ISSUE THREAD

**Issue by jonworek** [renchap/webpacker-react#24]
Hi.  This is a great project.  Thanks for taking the initiative to work on this.

I'm running into some trouble with an app I have deployed to production (all works well in development).  I'm registering a component then attempting to render it from my view.  But I'm getting the error in the Chrome dev console:

`webpacker-react: cant render a component that has not been registered: Hello`

Stepping into the source, it seems like there's a problem caused by the minified JS.

In my `packs/application.js` I have:

```
import Hello from 'components/hello.jsx'

WebpackerReact.register(Hello);
```

Inside `WebpackerReact.register(Hello);`, `Hello` has a minified value of `t`, and that is what is getting registered and stored inside the collection of registered components.

When I go to render with:
`<%= react_component("Hello", name: (current_user.try(:name) || "visitor") + " from react") %>`

The lookup being done in `WebpackerReact.addEventEventhandlers()` is only finding `t` rather than `Hello`, resulting in the:

`webpacker-react: cant render a component that has not been registered: Hello`

error, and the component not being rendered.

I'm not sure if the issue lies here, or with webpacker, or if there is some configuration I can change.

Much appreciated for any help you can give!

**Comment by renchap** [comment]
Please see #23 for a workaround. I will release 0.2.0 as soon as I get some time for a proper fix.

**Comment by renchap** [comment]
The new version is now released and fixes this issue!
Please look at the CHANGELOG, the API changed (`setup` replaced `register`).

**Comment by jonworek** [comment]
It works!!  Thank you!!!
