### ISSUE TITLE
Invariant Violation: addComponentAsRefTo(...)

### ISSUE THREAD

**Issue by cinqi** [renchap/webpacker-react#26]
This might due to my React components but this did appear after upgrading to 0.2.0. Most of the main components have componentDidMount that actually makes an ajax call to get initial data, which is something that I'm probably moving away from, mentioning this as the error is logged from this part of the code. 

So, after upgrading to 0.2.0 I'm getting this error:

`Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).`

I have a setup where I components in app/javascript like this:

app/javascript/clients
app/javascripts/products
etc

In the packs folder I have one file per the main component like this:

```
import Clients from '../clients';
import WebpackerReact from 'webpacker-react'
WebpackerReact.setup({Clients})

```

And in views I have:

```
<% content_for :head do %>
  <%= javascript_pack_tag 'clients' %>
<% end %>
<%= react_component('Clients') %>
```

In addition to these per page components I do have one component that is common for all pages. So in the application layout I have:

```
<head>
...
  <%= javascript_pack_tag 'flash_messages' %>
  <%= yield :head %>
</head>
...
 <%= react_component('FlashMessages') %>
```

Edit:
This error goes away if I move all imports to flash_message pack file and import only that file to application layout...

```
import Clients from '../clients';
import Products from '../products';
import WebpackerReact from 'webpacker-react'
WebpackerReact.setup({Clients, Products })
```

**Comment by renchap** [comment]
> or you have multiple copies of React loaded
This is probably the issue.

When you have multiple packs, Webpack considers each of them independently. This means that all your dependencies are bundled into each pack, and thus you have the React code loaded multiple times.

If you go with multiple pack files for different parts of your app, you need to tell Webpack to create a special bundle with all your common code (shared between multiple Webpack entry points, here meaning your pack files).

To do so, the easiest way is to use Webpack's [CommonChunkPlugin](https://webpack.js.org/plugins/commons-chunk-plugin/).

A simple config that should work is to change your `config/webpack/shared.js` to:
```es6
...
  plugins: [
  ...,
  new webpack.optimize.CommonsChunkPlugin({
    name: "commons",
    filename: "commons.js",
    minChunks: 2,
  })
```

This should create a new JS file called `commons.js` containing all code that is used by 2 or more pack files. You need to load it before any other packfiles: `<%= javascript_pack_tag 'commons' %>`

This way React (and other dependancies) will only be in this file and loaded once. This also means your  visitors will load less JS, as the commons file will be cached between requests and your page-specific pack files will be far smaller.

**Comment by cinqi** [comment]
Ok, I'll explore this, in the meantime I'll probably go with one huge file. As this is not related to webpacker-react itself, I'll close this issue.
