### ISSUE TITLE
render in a different tag than div?

### ISSUE THREAD

**Issue by tirdadc** [renchap/webpacker-react#30]
Right now the default tag the React component is rendered in is a `div`, is it possible to render in something else with a param? I tried `span: 'div'` without any luck.

**Comment by daninfpj** [comment]
This is not supported right now, but it‘s pretty easy to implement. You can add an option sent to the `render` function and then have `content_tag` use that if present, defaulting to `div`.

[Take a look at the relevant line](https://github.com/renchap/webpacker-react/blob/master/lib/webpacker/react/component.rb#L15).

**Comment by renchap** [comment]
I just released version 0.3.0 with this feature!
