### ISSUE TITLE
Differences between webpacker-react and react_on_rails

### ISSUE THREAD

**Issue by justin808** [renchap/webpacker-react#39]
Are there any compelling features offered by webpacker-react with react_on_rails now going directly off webpacker? Do you guys need any help from me? Want to help me with React on Rails? 

Here are the PRs that put React on Rails on top of Webpacker:

* https://github.com/rails/webpacker/pull/601
* https://github.com/shakacode/react_on_rails/pull/908

Other links:

* [9.0.0.beta.1 Gem](https://rubygems.org/gems/react_on_rails/versions/9.0.0.beta.1)
* [Video of GORUCO 2017 talk](https://www.youtube.com/watch?v=SGkTvKRPYrk)

**Comment by eadz** [comment]
Hi!

I had a look at both projects, and I think there are some differences in approach. 

Webpacker-react simply provides a way to render react components in the frontend of your app. The instructions all fit on the readme, and it seems to work well in my experience out of the box with rails 5.1 and turbolinks. 

React on rails is an opinionated framework, much more than a library.

While React on Rails may be a superset of functionality that webpacker-react provides, it is more complex to understand ( a book vs a readme ) and given that it uses react-router, may not be suitable for someone who just wants to add a react component to their frontend. 

If I was to suggest a way forward, I wonder whether react-on-rails can be split into clearly defined modules - the rendering of a react component to a page may be one of those modules ( aka webpacker-react ) and for example integration of react-router from the server side may be another module, integration with redux another.

Long term this will benefit to both projects!

**Comment by renchap** [comment]
As @eadz said, `webpacker-react` is indented to be as simple and minimalist as possible to work with a standard Rails environment.

I saw that `react_on_rails` is now using Webpacker 3, but I feel it brings a lot more than just React. It provides a nice integrated solution, but it does a lot more than this project and adds some complexity.
