### ISSUE TITLE
How do you nest components?

### ISSUE THREAD

**Issue by brentdodell** [renchap/webpacker-react#40]
Hello. I was wondering if there was a way to nest components with `react_component`? It seems like it would be handy for that method to accept a block, to enable nesting.

I.E.
```ERB
<%= react_component('Container') do %>
  <%= react_component('Grid') do %>
    <%= react_component('Cell') do %>
      Cell Contents 1
    <% end %>

    <%= react_component('Cell') do %>
      Cell Contents 2
    <% end %>

    <%= react_component('Cell') do %>
      Cell Contents 3
    <% end %>
  <%= end %>
<% end %>
```

**Comment by renchap** [comment]
Hi Brent. This is not the way React works. You need to have your nested components called in your `Container`'s `render` method: https://facebook.github.io/react/docs/components-and-props.html#composing-components

**Comment by brentdodell** [comment]
Thank you. I'm really fresh to React, and I think I realized that a couple days after asking this.
