### ISSUE TITLE
Register Multiple Components

### ISSUE THREAD

**Issue by Petercopter** [renchap/webpacker-react#45]
Kind of a noob here, so be gentle. I'm moving from webpack-rails with a custom setup to do basically the same thing as webpacker-react.

I'm trying to register multiple individual components for rendering on the page. I'm not seeing any documentation about this, which makes me think I'm barking up the wrong tree, but here goes.

I've tried
```
  = javascript_pack_tag 'pack1', 'pack2'
```
and
```
  = javascript_pack_tag 'pack1'
  = javascript_pack_tag 'pack2'
```
Both result in
```
webpacker-react: cant render a component that has not been registered: Pack2
```
It always registers the first one, but not the second. I'm getting the feeling that maybe I need to combine all components into a pack, and then render them on the page?

Right now we have a bunch of separate components, which we bolt onto the page using a Ruby helper very similar to `react_component` (it's even named the same).

Any direction would be much appreciated, thanks very much for webpacker-react!

**Comment by renchap** [comment]
In Webpacker, a pack is a webpack entry point. In `app/javascript/packs` you need to only have your pack files. Most of the time, you will go with only one pack.

You then need to include the `<script>` tag for this pack in your layout using `javascript_pack_tag`.

Once this general setup is done, in your pack you can register 1 or many React components, and then mount them to your page using the `react_component` helper.

**Comment by Petercopter** [comment]
@renchap Thanks for the quick response! I'm going to digest this, and learn more about what's going on. 🍺  cheers!

**Comment by renchap** [comment]
Closing this issue as it seems to be solved, feel free to reopen!
