### ISSUE TITLE
Compatibility with Rails 5.1.4

### ISSUE THREAD

**Issue by navjeetc** [renchap/webpacker-react#46]
Is this compatible with Rails 5.1.4? I keep getting the  error: 

`webpacker-react: cannot render a component that has not been registered: Hello`

I started with Ruby 2.3.3 and Rails 5.1.4 using the command
`rails new myapp --webpack=react`
and copied the files hello_react.js and hello.jsx from webpack-react-example into app/javascript/packs and app/javascript/components folders and added 
`<%= javascript_pack_tag 'hello_react' %>`
to application.html.erb. Created a new Home controller with index action and added 
`<%= react_component('Hello', name: 'React') %>` 
to index.html.erb. Ran 
`./bin/webpack` 
followed by `rails s`

**Comment by renchap** [comment]
The syntax changed to register the components changed: https://github.com/renchap/webpacker-react/blob/master/CHANGELOG.md#020---2017-03-20

The example is not up-to-date.

**Comment by navjeetc** [comment]
That was it. I changed the code from
`WebpackerReact.setup(Hello);`
to
`WebpackerReact.setup({Hello});`
and it worked fine.
