### ISSUE TITLE
Importing styles from within component does not render them

### ISSUE THREAD

**Issue by JeffreyCheng92** [renchap/webpacker-react#54]
Im new to webpack and the confgis but cannot understand why inside my component (`user.jsx`), Im requiring the corresponding `user.scss` file but for some reason it is not rendering. The file is definitely being required somehow because breaking the `scss` file by having incomplete `{}` will throw an error. 

Im using `style-loader', `css-loader`, and `sass-loader` following some guides but it does not seem to work. I do not want to put my styling into `app/assets/stylesheets` because I dont want the application to load all the styles everytime my single-page-app renders.

```
# user.jsx
import styles from '../styles/user.scss';
.
render() {
  return <div className='red-block'> This is red </div>
}
```

```
#user.scss
.red-block { background-color: red; }
```

```
app
└──javascripts
    └──home
    └──user
        └──components
            user.jsx
        └──styles
            user.scss
        index.js
```

I found this config below but am not sure this is quite right, there seems to be many variations to this.

Installation command: `yarn add webpack babel-core babel-loader babel-preset-react babel-preset-es2015 node-sass css-loader sass-loader style-loader`

```
# config/webpack/development.js

const environment = require('./environment')

module.exports = {
    module: {
        rules: [{
            test: /\.scss$/,
            use: [{
                loader: "style-loader" // creates style nodes from JS strings
            }, {
                loader: "css-loader" // translates CSS into CommonJS
            }, {
                loader: "sass-loader" // compiles Sass to CSS
            }]
        }]
    }
};
module.exports = environment.toWebpackConfig()

```

Any help would be appreciated!

**Comment by aaronsama** [comment]
Make sure you are also loading the stylesheet for your pack in `application.html.erb` as described here: https://github.com/rails/webpacker#usage

Once you start adding styles to your components, assuming your entry is called `application.js`, you must also include `application.css`

```
<%= javascript_pack_tag 'application' %>
<%= stylesheet_pack_tag 'application' %>
```

I don't think you need to edit your loaders in Webpack's configuration with the latest version of `webpacker`.

Hope this helps.

**Comment by jbharat** [comment]
Have faced this issue, code given by @aaronsama solves it. Just include stylesheet_pack_tag

**Comment by JeffreyCheng92** [comment]
Thats exactly what it was @aaronsama. Funny how so many guides out there just ignore this point and choose to use the manifest file that comes packaged with rails. Thanks a lot!
