### ISSUE TITLE
License Required

### ISSUE THREAD

**Issue by bootcoder** [renchap/webpacker-react#60]
Please add a license.

MIT, New BSD, CC0-1.0.... really any open source license so I can keep your gem in my project. Otherwise I'm going to be forced to rip it out and that would be decidedly not great. 

I'm three weeks into building the framework for converting our large Angular/Rails app over to start using React. I really like the functionality and ease of render that `webpacker-react` gives me but... 

We have strict open source licensing protocols at my company and I just noticed that you have no license listed whatsoever. (At least in so far as I can see)

Action appreciated and thanks in advance.

------------------------------

As a side and unrelated note, I'm doing a few things that seem unconventional in order to establish a piece by piece conversion strategy. If I were to put together a small sample app employing these techniques would there be any chance I could get a quick once over to ensure I'm not setting myself up for trouble down the road?

**Comment by renchap** [comment]
Thanks, I never saw that the license file was missing. This is now fixed!

I do not have much time currently, but if you send me a link to your app I can have a quick look, please tell me what to look for in an email :)
