### ISSUE TITLE
bind knockout variable to react_component helper

### ISSUE THREAD

**Issue by tomkra** [renchap/webpacker-react#62]
Hello,

we are using knockout for front end and slowly migrating to react. Is there any posibility to bing knockout observable as prop to ```react_component``` helper?

For example in my knockout I have:
```
active_chapter_id = ko.observable()
```
I'm trying to make comments section as react component and when I change active chapter, I need to pass new value from knockout to react_component helper.

I've tried these solutions, but non of them workded:
```
= react_component "ChapterCommentsSection", {}, data: {bind: "attr: {activeChapterId: 'active_chapter_id'"}

= react_component "ChapterCommentsSection", {}, data: {bind: "attr: {data-react-props: {activeChapterId: 'active_chapter_id'"}

= react_component "ChapterCommentsSection", {}, data: {bind: "attr: {'data-react-props': '{activeChapterId: active_chapter_id}' }"}
```
Is there any easy solution to this or did someone deal with similar problem? Thank you.

**Comment by tomkra** [comment]
After some googling stupid question. Closing.

**Comment by BookOfGreg** [comment]
@tomkra what was the answer? It may help people in the future to know.

**Comment by tomkra** [comment]
I'm not sure if this is correct solution, however It works like a charm and I didn't have to install another libraries.

So suppose I have ```@active_chapter_id = ko.observable()``` which stores current chapter and I need this variable pass to my react component anytime it changes. To do so I'm doing following:

_for javascript I'm combinig coffeescript with es5 syntax:_

1. subscribe active_chapter_id and call own event
```
@active_chapter_id.subscribe (new_value, old_value) =>
      document.getElementById("chapter_comments").dispatchEvent(new CustomEvent('datachange', { detail: {activeChapterId: new_value} }))
```
2. In my ```packs/chapter_component.jsx``` I'm waiting for my own event and then passing value to my component:
```
import React from 'react';
import ReactDOM from 'react-dom';

import ChapterComments from "../components/chapter_comment";

document.getElementById("chapter_comments").addEventListener("datachange", function(event) {
  const activeChapterId = event.detail.activeChapterId;

  if (activeChapterId) {
    ReactDOM.render(
      <ChapterCommentsSection activeChapterId={activeChapterId} />,
      document.getElementById("chapter_comments")
    )
  }
});

Hope this helps or maybe there is clearer solution for this. However this works just fine.
